package generator

import "google.golang.org/protobuf/compiler/protogen"

const (
	errorsPackage = protogen.GoImportPath("github.com/shiw-yang/strike/errors")
	fmtPackage    = protogen.GoImportPath("fmt")
)

// GeneratedFile generates a xxx_errors.pb.go file
func GeneratedFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Enums) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_errors.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-errors. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.QualifiedGoIdent(fmtPackage.Ident(""))
	// generateFileContent(gen, file, g)
	return g
}

func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	panic("unimplemented")
}
